name: Android Appium Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '18.0.2'

    - name: Download and install Android Studio
      run: |
        echo "Downloading Android Studio..."
        Invoke-WebRequest -Uri "https://redirector.gvt1.com/edgedl/android/studio/install/2024.1.1.11/android-studio-2024.1.1.11-windows.exe" -OutFile "android-studio-2024.1.1.11-windows.exe"
        echo "Installing Android Studio..."
        Start-Process -FilePath "android-studio-2024.1.1.11-windows.exe" -ArgumentList "/S" -Wait
        echo "Android Studio installed."
      shell: pwsh

    - name: Set up Android SDK
      run: |
        echo "Setting up Android SDK..."
        echo "sdk.dir=$env:ANDROID_HOME" > local.properties
        echo "Accepting SDK licenses..."
        Start-Process -FilePath "$env:ANDROID_HOME\tools\bin\sdkmanager.bat" -ArgumentList "--licenses" -NoNewWindow -Wait -PassThru | ForEach-Object { $_.StandardInput.WriteLine("y") }
        echo "Installing platform tools and system images..."
        $result = Start-Process -FilePath "$env:ANDROID_HOME\tools\bin\sdkmanager.bat" -ArgumentList "platform-tools", "platforms;android-30", "system-images;android-30;google_apis;x86_64" -NoNewWindow -Wait -PassThru
        $result.WaitForExit()
        echo "Android SDK setup completed."
      shell: pwsh

    - name: Create AVD
      run: |
        echo "Creating AVD..."
        Start-Process -FilePath "$env:ANDROID_HOME\tools\bin\avdmanager.bat" -ArgumentList "create avd -n test_avd -k \"system-images;android-30;google_apis;x86_64\" -d \"pixel\"" -NoNewWindow -Wait
        echo "Starting AVD..."
        Start-Process -FilePath "$env:ANDROID_HOME\emulator\emulator.exe" -ArgumentList "-avd test_avd -no-snapshot-load -no-snapshot-save -no-window" -NoNewWindow -Wait
        echo "AVD started."
      shell: pwsh

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Appium
      run: |
        echo "Installing Appium..."
        npm install -g appium
        echo "Appium installed."
      shell: pwsh

    - name: Run Appium server
      run: |
        echo "Starting Appium server..."
        Start-Process -FilePath "appium" -ArgumentList "--log-level info" -NoNewWindow -Wait
        echo "Appium server started."
      shell: pwsh

    - name: Run Appium tests
      run: |
        echo "Running Appium tests..."
        mvn test
        echo "Appium tests completed."
      shell: pwsh
