name: CI with Screenshots

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install scrot for screenshots
      run: sudo apt-get update && sudo apt-get install -y scrot

    - name: Take screenshots at intervals
      run: |
        mkdir screenshots
        for i in {1..5}; do
          scrot "screenshots/screenshot_$i.png"
          sleep 10
        done

    - name: Upload screenshots
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: screenshots/
